import React, { useMemo, useState } from 'react'
import type { CoreApi, EnvironmentProfile, EnvironmentStoreV2, MemoryPolicy, UiSnapshot } from './types'
import { ReactUiStore } from './store'

interface StudioForm {
  id: string
  name: string
  targetProfileId: string
  sourceFileName: string
  model: string
  modelProvider: string
  reasoning: string
  developerInstructions: string
  baseInstructions: string
  approvalPolicy: string
  sandbox: string
  serviceTier: string
  memoryUse: NonNullable<MemoryPolicy['use']>
  memoryGenerate: NonNullable<MemoryPolicy['generate']>
  configText: string
}

const blankForm = (): StudioForm => ({
  id: '', name: '', targetProfileId: '', sourceFileName: '', model: '', modelProvider: '', reasoning: '',
  developerInstructions: '', baseInstructions: '', approvalPolicy: '', sandbox: '', serviceTier: '',
  memoryUse: 'inherit', memoryGenerate: 'inherit', configText: '{}',
})

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value))
}

function rawProfileId(profile: EnvironmentProfile) {
  return profile.id.startsWith('studio:') ? profile.id.slice('studio:'.length) : profile.id
}

function profileToForm(profile: EnvironmentProfile): StudioForm {
  const config = clone(profile.config || {}) as Record<string, unknown>
  const reasoning = String(config.model_reasoning_effort || '')
  delete config.model_reasoning_effort
  const targetProfileId = profile.source === 'file' || profile.source === 'studio-override' ? profile.id : ''
  return {
    id: rawProfileId(profile),
    name: profile.name || rawProfileId(profile),
    targetProfileId,
    sourceFileName: profile.sourceFileName || (targetProfileId ? `${targetProfileId}.config.toml` : ''),
    model: profile.model || '',
    modelProvider: profile.modelProvider || '',
    reasoning,
    developerInstructions: profile.developerInstructions || '',
    baseInstructions: profile.baseInstructions || '',
    approvalPolicy: profile.approvalPolicy || '',
    sandbox: profile.sandbox || '',
    serviceTier: profile.serviceTier || '',
    memoryUse: profile.memoryPolicy?.use || 'inherit',
    memoryGenerate: profile.memoryPolicy?.generate || 'inherit',
    configText: JSON.stringify(config, null, 2),
  }
}

function likelySecret(text: string) {
  return /\bsk-[A-Za-z0-9_-]{16,}\b|\b(?:api[_-]?key|access[_-]?token|refresh[_-]?token|token|password|secret|authorization|bearer|credential)["']?\s*[:=]|\bBearer\s+[A-Za-z0-9_./+=-]{12,}|[a-z][a-z0-9+.-]*:\/\/[^/\s@]+:[^/\s@]+@/i.test(text)
}

function tomlString(value: unknown) {
  return JSON.stringify(String(value ?? ''))
}

function tomlKey(value: unknown) {
  const key = String(value ?? '')
  return /^[A-Za-z0-9_-]+$/.test(key) ? key : tomlString(key)
}

function tomlValue(value: unknown): string {
  if (typeof value === 'string') return tomlString(value)
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  if (typeof value === 'number' && Number.isFinite(value)) return String(value)
  if (Array.isArray(value)) return `[${value.map(tomlValue).join(', ')}]`
  if (value && typeof value === 'object') return `{ ${Object.entries(value).map(([key, item]) => `${tomlKey(key)} = ${tomlValue(item)}`).join(', ')} }`
  throw new Error(`无法导出 TOML 值：${String(value)}`)
}

function appendTomlConfig(lines: string[], value: Record<string, unknown>, path: string[] = []) {
  const entries = Object.entries(value || {})
  const scalars = entries.filter(([, item]) => !(item && typeof item === 'object' && !Array.isArray(item)))
  const tables = entries.filter(([, item]) => item && typeof item === 'object' && !Array.isArray(item))
  if (path.length) lines.push('', `[${path.map(tomlKey).join('.')}]`)
  for (const [key, item] of scalars) lines.push(`${tomlKey(key)} = ${tomlValue(item)}`)
  for (const [key, item] of tables) appendTomlConfig(lines, item as Record<string, unknown>, [...path, key])
}

function profileToml(form: StudioForm, inputConfig: Record<string, unknown>) {
  const lines: string[] = ['# Generated by Codex++ Environment Injector React Studio', `# Source: ${form.sourceFileName || 'local environment'}`, '']
  const scalar: Array<[string, unknown]> = [
    ['model', form.model], ['model_provider', form.modelProvider], ['model_reasoning_effort', form.reasoning],
    ['approval_policy', form.approvalPolicy], ['sandbox_mode', form.sandbox], ['service_tier', form.serviceTier],
    ['developer_instructions', form.developerInstructions], ['base_instructions', form.baseInstructions],
  ]
  for (const [key, value] of scalar) if (value !== '') lines.push(`${key} = ${tomlValue(value)}`)
  const config = clone(inputConfig)
  delete config.model_reasoning_effort
  const memories: Record<string, boolean> = {}
  if (form.memoryUse !== 'inherit') memories.use_memories = form.memoryUse === 'on'
  if (form.memoryGenerate !== 'inherit') memories.generate_memories = form.memoryGenerate === 'on'
  if (Object.keys(memories).length) config.memories = memories
  appendTomlConfig(lines, config)
  lines.push('')
  return lines.join('\n')
}

function Field({ label, children, full = false }: { label: string; children: React.ReactNode; full?: boolean }) {
  return <label className={`ei-studio-field${full ? ' ei-studio-field-full' : ''}`}><span>{label}</span>{children}</label>
}

function TextInput(props: React.InputHTMLAttributes<HTMLInputElement>) {
  return <input className="ei-studio-input" {...props} />
}

function SelectInput(props: React.SelectHTMLAttributes<HTMLSelectElement>) {
  return <select className="ei-studio-input" {...props} />
}

export function StudioDialog({ api, store, core }: { api: CoreApi; store: ReactUiStore; core: UiSnapshot }) {
  const profiles = useMemo(() => core.profiles.filter((profile) => profile.id !== 'base'), [core.profiles])
  const [selectedId, setSelectedId] = useState<string>('')
  const [selectedStorageKey, setSelectedStorageKey] = useState<string>('')
  const [form, setForm] = useState<StudioForm>(blankForm)
  const [useNext, setUseNext] = useState(true)
  const [editorTab, setEditorTab] = useState<'basic' | 'instructions' | 'runtime' | 'advanced'>('basic')
  const [message, setMessage] = useState('可新建环境，也可选择文件环境并保存为本地覆盖。')
  const [kind, setKind] = useState<'info' | 'success' | 'error'>('info')

  const update = <K extends keyof StudioForm>(key: K, value: StudioForm[K]) => setForm((current) => ({ ...current, [key]: value }))

  const selectProfile = (profile: EnvironmentProfile) => {
    const rawId = rawProfileId(profile)
    const target = profile.source === 'file' || profile.source === 'studio-override' ? profile.id : ''
    setSelectedId(profile.id)
    setSelectedStorageKey(target ? `override:${target}` : rawId)
    setForm(profileToForm(profile))
    setEditorTab('basic')
    setKind('info')
    setMessage(target ? `文件环境 ${profile.name} 将保存为本地覆盖，原文件不变。` : `正在编辑本地环境 ${profile.name}。`)
  }

  const createNew = () => {
    setSelectedId('')
    setSelectedStorageKey('')
    setForm(blankForm())
    setEditorTab('basic')
    setKind('info')
    setMessage('创建新的本地环境。')
  }

  const validate = () => {
    if (!/^[A-Za-z0-9_-]+$/.test(form.id)) return '环境 ID 只能包含英文、数字、下划线和减号'
    if (form.developerInstructions.length > 40_000 || form.baseInstructions.length > 40_000) return '提示词不能超过 40000 个字符'
    try {
      const config = JSON.parse(form.configText || '{}')
      if (!config || typeof config !== 'object' || Array.isArray(config)) return 'Additional Config 必须是 JSON 对象'
    } catch { return 'Additional Config JSON 格式无效' }
    if (![form.model, form.modelProvider, form.developerInstructions, form.baseInstructions, form.approvalPolicy, form.sandbox, form.serviceTier, form.reasoning].some(Boolean)
      && form.memoryUse === 'inherit' && form.memoryGenerate === 'inherit' && form.configText.trim() === '{}') return '请至少提供一项环境设置'
    const key = form.targetProfileId ? `override:${form.targetProfileId}` : form.id
    if (Object.hasOwn(core.environmentStore.profiles, key) && key !== selectedStorageKey) return '环境 ID 已存在，不能覆盖另一环境'
    const countAfter = Object.keys(core.environmentStore.profiles).length
      + (Object.hasOwn(core.environmentStore.profiles, key) ? 0 : 1)
      - (selectedStorageKey && selectedStorageKey !== key && Object.hasOwn(core.environmentStore.profiles, selectedStorageKey) ? 1 : 0)
    if (countAfter > 50) return '最多保存 50 个本地环境'
    return ''
  }

  const save = () => {
    const error = validate()
    if (error) { setKind('error'); setMessage(error); return }
    let config: Record<string, unknown>
    try { config = JSON.parse(form.configText || '{}') } catch { return }
    if (form.reasoning) config.model_reasoning_effort = form.reasoning
    if (likelySecret(form.developerInstructions) || likelySecret(form.baseInstructions) || likelySecret(form.configText)) {
      setKind('error'); setMessage('敏感字段不允许写入环境；请改用环境变量名或凭据存储'); return
    }
    const next = clone(core.environmentStore) as EnvironmentStoreV2
    const storageKey = form.targetProfileId ? `override:${form.targetProfileId}` : form.id
    if (selectedStorageKey && selectedStorageKey !== storageKey) delete next.profiles[selectedStorageKey]
    const previous = next.profiles[storageKey]
    next.profiles[storageKey] = {
      id: form.id,
      name: form.name.trim() || form.id,
      ...(form.targetProfileId ? { targetProfileId: form.targetProfileId, origin: 'file-override' } : { origin: 'local' }),
      sourceFileName: form.sourceFileName,
      model: form.model.trim(),
      modelProvider: form.modelProvider.trim(),
      developerInstructions: form.developerInstructions,
      baseInstructions: form.baseInstructions,
      approvalPolicy: form.approvalPolicy,
      sandbox: form.sandbox,
      serviceTier: form.serviceTier.trim(),
      memoryPolicy: { use: form.memoryUse, generate: form.memoryGenerate },
      config,
      createdAt: (previous as any)?.createdAt || Date.now(),
      updatedAt: Date.now(),
    } as any
    try {
      api.saveProfile(next.profiles[storageKey], { previousKey: selectedStorageKey, expectedRevision: core.environmentStore.revision })
    } catch {
      setKind('error'); setMessage('保存失败：数据无效、环境已变化或存储不可写。请重新加载检查。'); return
    }
    const environmentId = form.targetProfileId || `studio:${form.id}`
    setSelectedId(environmentId)
    setSelectedStorageKey(storageKey)
    if (useNext) {
      try { api.setNext(environmentId) } catch {
        setKind('error'); setMessage('环境已保存，但下次环境选择保存失败'); return
      }
    }
    setKind('success')
    setMessage(form.targetProfileId ? `已保存 ${form.targetProfileId} 的本地覆盖。` : `已保存环境 ${form.name || form.id}。`)
  }

  const remove = () => {
    if (!selectedStorageKey || !core.environmentStore.profiles[selectedStorageKey]) return
    const isOverride = Boolean(form.targetProfileId)
    if (!window.confirm(isOverride ? `恢复文件环境“${form.targetProfileId}”并删除本地覆盖？` : `删除环境“${form.name || form.id}”？`)) return
    const next = clone(core.environmentStore) as EnvironmentStoreV2
    delete next.profiles[selectedStorageKey]
    try { api.replaceEnvironmentStore(next) } catch {
      setKind('error'); setMessage('删除未保存：环境已变化或存储不可写'); return
    }
    createNew()
    setKind('success')
    setMessage(isOverride ? `已恢复文件环境 ${form.targetProfileId}。` : '环境已删除。')
  }

  const exportToml = () => {
    const invalid = validate()
    if (invalid || likelySecret(form.developerInstructions) || likelySecret(form.baseInstructions) || likelySecret(form.configText)) {
      setKind('error'); setMessage(invalid || '敏感内容不允许导出'); return
    }
    let config: Record<string, unknown> = {}
    try { config = JSON.parse(form.configText || '{}') } catch {}
    try { api.validateProfileData({ ...form, config }) } catch {
      setKind('error'); setMessage('配置无效或包含敏感字段，已拒绝导出'); return
    }
    const blob = new Blob([profileToml(form, config)], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const anchor = document.createElement('a')
    anchor.href = url
    anchor.download = `${form.id || 'environment'}.config.toml`
    anchor.click()
    setTimeout(() => URL.revokeObjectURL(url), 1000)
  }

  const loadAgents = async (file: File | undefined) => {
    if (!file) return
    if (file.size > 256 * 1024) { setKind('error'); setMessage('AGENTS.md 最大允许 256 KiB'); return }
    const text = await file.text()
    update('developerInstructions', text.slice(0, 40_000))
    if (!form.name) update('name', file.name.replace(/\.md$/i, ''))
    if (!form.id) update('id', file.name.replace(/\.md$/i, '').toLowerCase().replace(/[^a-z0-9_-]+/g, '-').replace(/^-|-$/g, ''))
    setKind('success')
    setMessage(`已载入 ${file.name}`)
  }

  return <div className="ei-backdrop ei-studio-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) store.closeStudio() }}>
    <section className="ei-studio-dialog" role="dialog" aria-modal="true" aria-label="环境注入器编辑器">
      <header className="ei-header"><div className="ei-header-copy"><h2>环境注入器</h2><p>React Studio · 环境、提示词、Memories 与权限</p></div><div className="ei-header-actions"><button className="ei-button" type="button" onClick={() => { store.closeStudio(); store.openMode('tutorial') }}>使用教程</button><button className="ei-icon-button" type="button" onClick={() => store.closeStudio()} aria-label="关闭">×</button></div></header>
      <div className="ei-studio-layout">
        <aside className="ei-studio-sidebar"><ButtonLike label="+ 新建环境" onClick={createNew} primary />{profiles.map((profile) => <button className="ei-studio-profile" data-active={selectedId === profile.id} type="button" key={profile.id} onClick={() => selectProfile(profile)}><strong>{profile.name}</strong><small>{profileDetail(profile)}</small></button>)}</aside>
        <main className="ei-studio-editor">
          <div className="ei-studio-editor-head">
            <div><strong>{form.name || form.id || '新环境'}</strong><span>{form.targetProfileId ? '文件覆盖' : selectedStorageKey ? '本地环境' : '未保存'}</span></div>
            <nav className="ei-studio-tabs" aria-label="环境编辑区域">{([['basic','基础'],['instructions','提示词'],['runtime','运行策略'],['advanced','高级']] as const).map(([id,label]) => <button type="button" key={id} aria-selected={editorTab === id} onClick={() => setEditorTab(id)}>{label}</button>)}</nav>
          </div>
          <div className="ei-studio-content">
            {editorTab === 'basic' ? <div className="ei-studio-grid ei-studio-grid-compact">
              <Field label="环境 ID"><TextInput value={form.id} disabled={Boolean(form.targetProfileId)} onChange={(event) => update('id', event.target.value)} /></Field>
              <Field label="名称"><TextInput value={form.name} onChange={(event) => update('name', event.target.value)} /></Field>
              <Field label="模型"><TextInput value={form.model} onChange={(event) => update('model', event.target.value)} /></Field>
              <Field label="Provider"><TextInput value={form.modelProvider} onChange={(event) => update('modelProvider', event.target.value)} /></Field>
            </div> : null}
            {editorTab === 'instructions' ? <div className="ei-studio-section">
              <label className="ei-studio-import" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); void loadAgents(event.dataTransfer.files?.[0]) }}>导入 AGENTS.md<input type="file" accept=".md,text/markdown,text/plain" onChange={(event) => void loadAgents(event.target.files?.[0])} /></label>
              <Field label="Developer Instructions" full><textarea className="ei-textarea ei-studio-textarea" value={form.developerInstructions} onChange={(event) => update('developerInstructions', event.target.value)} /></Field>
              <Field label="Base Instructions" full><textarea className="ei-textarea ei-studio-textarea" value={form.baseInstructions} onChange={(event) => update('baseInstructions', event.target.value)} /></Field>
            </div> : null}
            {editorTab === 'runtime' ? <div className="ei-studio-grid ei-studio-grid-compact">
              <Field label="推理强度"><SelectInput value={form.reasoning} onChange={(event) => update('reasoning', event.target.value)}><option value="">继承</option>{['minimal','low','medium','high','xhigh'].map((value) => <option key={value}>{value}</option>)}</SelectInput></Field>
              <Field label="Service Tier"><TextInput value={form.serviceTier} onChange={(event) => update('serviceTier', event.target.value)} /></Field>
              <Field label="审批策略"><SelectInput value={form.approvalPolicy} onChange={(event) => update('approvalPolicy', event.target.value)}><option value="">继承</option><option value="untrusted">untrusted</option><option value="on-request">on-request</option><option value="never">never</option></SelectInput></Field>
              <Field label="沙箱"><SelectInput value={form.sandbox} onChange={(event) => update('sandbox', event.target.value)}><option value="">继承</option><option value="read-only">read-only</option><option value="workspace-write">workspace-write</option><option value="danger-full-access">danger-full-access</option></SelectInput></Field>
              <Field label="Memory 读取"><SelectInput value={form.memoryUse} onChange={(event) => update('memoryUse', event.target.value as StudioForm['memoryUse'])}><option value="inherit">继承</option><option value="on">开启</option><option value="off">关闭</option></SelectInput></Field>
              <Field label="Memory 生成"><SelectInput value={form.memoryGenerate} onChange={(event) => update('memoryGenerate', event.target.value as StudioForm['memoryGenerate'])}><option value="inherit">继承</option><option value="on">开启</option><option value="off">关闭</option></SelectInput></Field>
            </div> : null}
            {editorTab === 'advanced' ? <div className="ei-studio-section"><p className="ei-help">仅填写经过检查的附加 JSON；模型、提示词和运行策略请使用前面的表单。</p><Field label="Additional Config JSON" full><textarea className="ei-textarea ei-studio-code" value={form.configText} onChange={(event) => update('configText', event.target.value)} /></Field></div> : null}
          </div>
          <footer className="ei-studio-savebar"><label className="ei-toggle"><input type="checkbox" checked={useNext} onChange={(event) => setUseNext(event.target.checked)} />设为下个对话</label><span className="ei-studio-spacer" /><ButtonLike label="导出" onClick={exportToml} /><ButtonLike label={form.targetProfileId ? '恢复' : '删除'} onClick={remove} disabled={!selectedStorageKey || !core.environmentStore.profiles[selectedStorageKey]} /><ButtonLike label={form.targetProfileId ? '保存覆盖' : '保存'} onClick={save} primary /></footer>
          <p className="ei-status ei-studio-status" data-kind={kind}>{message}</p>
        </main>
      </div>
    </section>
  </div>
}

function ButtonLike({ label, onClick, primary = false, disabled = false }: { label: string; onClick(): void; primary?: boolean; disabled?: boolean }) {
  return <button className={`ei-button${primary ? ' ei-button-primary' : ''}`} type="button" onClick={onClick} disabled={disabled}>{label}</button>
}

function profileDetail(profile: EnvironmentProfile) {
  return [profile.source === 'file' ? '文件' : profile.source === 'studio-override' ? '本地覆盖' : '本地', profile.model, profile.modelProvider].filter(Boolean).join(' · ')
}
